using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace MiniMediator.Generator;

internal sealed class MiniMediatorGenerator : IIncrementalGenerator
{
    private const string IRequestHandler = nameof(IRequestHandler);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetHandler(ctx))
            .Where(static h => h is not null);

        var collected = handlers.Collect();

        context.RegisterSourceOutput(collected, static (spc, source) =>
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace MiniMediator.Core.Runtime;");
            sb.AppendLine("public static class GeneratedDispatch");
            sb.AppendLine("{");
            sb.AppendLine("    public static ValueTask<TResponse> Dispatch<TRequest, TResponse>(TRequest request, CancellationToken ct)");
            sb.AppendLine("        where TRequest : MiniMediator.Core.Abstractions.IRequest<TResponse>");
            sb.AppendLine("    {");

            foreach (var h in source)
            {
                if (h is null) continue;

                sb.AppendLine(h.GenerateCase());
            }

            sb.AppendLine("        throw new System.InvalidOperationException($\"No handler for {typeof(TRequest).Name}\");");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("MiniMediator.Generated.g.cs", sb.ToString());
        });
    }

    private static HandlerModel? GetHandler(GeneratorSyntaxContext ctx)
    {
        var classNode = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classNode) as INamedTypeSymbol;

        if (symbol is null)
            return null;

        foreach (var iface in symbol.AllInterfaces)
        {
            if (!iface.OriginalDefinition.ToDisplayString().Contains(IRequestHandler))
                continue;

            var requestType = iface.TypeArguments[0];
            var responseType = iface.TypeArguments[1];

            return new HandlerModel(
                symbol.ToDisplayString(),
                requestType.ToDisplayString(),
                responseType.ToDisplayString()
            );
        }

        return null;
    }

    private sealed record HandlerModel(
        string HandlerName,
        string RequestType,
        string ResponseType)
    {
        public string GenerateCase()
        {
            return $@"
        if (request is {RequestType} typed)
        {{
            var handler = new {HandlerName}();
            return handler.HandleAsync(typed, ct);
        }}";
        }
    }
}